/**
 * This class is generated by jOOQ
 */
package com.frotly.jooq.data;


import com.frotly.jooq.data.tables.Items;
import com.frotly.jooq.data.tables.Orderdetail;
import com.frotly.jooq.data.tables.Orders;
import com.frotly.jooq.data.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in learn
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table learn.items
	 */
	public static final Items ITEMS = com.frotly.jooq.data.tables.Items.ITEMS;

	/**
	 * The table learn.orderdetail
	 */
	public static final Orderdetail ORDERDETAIL = com.frotly.jooq.data.tables.Orderdetail.ORDERDETAIL;

	/**
	 * The table learn.orders
	 */
	public static final Orders ORDERS = com.frotly.jooq.data.tables.Orders.ORDERS;

	/**
	 * The table learn.user
	 */
	public static final User USER = com.frotly.jooq.data.tables.User.USER;
}
