/**
 * This class is generated by jOOQ
 */
package com.frotly.jooq.data.tables.records;


import com.frotly.jooq.data.tables.Items;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemsRecord extends UpdatableRecordImpl<ItemsRecord> implements Record6<Integer, String, Double, String, String, Timestamp> {

	private static final long serialVersionUID = 93969833;

	/**
	 * Setter for <code>learn.items.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>learn.items.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>learn.items.name</code>. 商品名称
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>learn.items.name</code>. 商品名称
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>learn.items.price</code>. 商品定价
	 */
	public void setPrice(Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>learn.items.price</code>. 商品定价
	 */
	public Double getPrice() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>learn.items.detail</code>. 商品描述
	 */
	public void setDetail(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>learn.items.detail</code>. 商品描述
	 */
	public String getDetail() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>learn.items.pic</code>. 商品图片
	 */
	public void setPic(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>learn.items.pic</code>. 商品图片
	 */
	public String getPic() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>learn.items.createtime</code>. 生产日期
	 */
	public void setCreatetime(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>learn.items.createtime</code>. 生产日期
	 */
	public Timestamp getCreatetime() {
		return (Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, Double, String, String, Timestamp> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, Double, String, String, Timestamp> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Items.ITEMS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Items.ITEMS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return Items.ITEMS.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Items.ITEMS.DETAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Items.ITEMS.PIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Items.ITEMS.CREATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDetail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPic();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getCreatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemsRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemsRecord value3(Double value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemsRecord value4(String value) {
		setDetail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemsRecord value5(String value) {
		setPic(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemsRecord value6(Timestamp value) {
		setCreatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemsRecord values(Integer value1, String value2, Double value3, String value4, String value5, Timestamp value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItemsRecord
	 */
	public ItemsRecord() {
		super(Items.ITEMS);
	}

	/**
	 * Create a detached, initialised ItemsRecord
	 */
	public ItemsRecord(Integer id, String name, Double price, String detail, String pic, Timestamp createtime) {
		super(Items.ITEMS);

		setValue(0, id);
		setValue(1, name);
		setValue(2, price);
		setValue(3, detail);
		setValue(4, pic);
		setValue(5, createtime);
	}
}
